[package]
name = "str0m-wincrypto"
version = "0.3.2"
description = "Supporting crate for str0m"
license = "MIT OR Apache-2.0"
repository = "https://github.com/algesten/str0m"
readme = "README.md"
edition = "2021"

# MSRV
rust-version = "1.81.0"

[features]
dtls13 = ["dep:dimpl"]

[dependencies]
tracing = "0.1.37"
str0m-proto = { version = "0.1.1", path = "../../proto" }
windows = { version = "0.58", features = [
  "Win32_Security_Cryptography",
  "Win32_Security_Authentication_Identity",
  "Win32_Security_Credentials",
  "Win32_System_Rpc",
] }
dimpl = { git = "https://github.com/algesten/dimpl", branch = "dtls13", default-features = false, features = ["aws-lc-rs", "rcgen"], optional = true }
