[package]
name = "dtls"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
thiserror = "1"

# Sadly no DTLS support in rustls.
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys = "^0.9"

net = { path = "../net" }
