[package]
name = "ice"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1"
thiserror = "1"
rand = "0.8"
#
net = { path = "../net" }

[dev-dependencies]
tracing-subscriber = { version = "0.3.16", features = ["env-filter", "std"] }
