[package]
name = "str0m-netem"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

# MSRV
rust-version = "1.81.0"

[dependencies]
fastrand = "2"
str0m-proto = { version = "0.1.0", path = "../proto" }
