[package]
name = "str0m-proto"
version = "0.1.0"
edition = "2021"

[features]
features = []
openssl = ["dep:openssl"]

[dependencies]
# DTLS made for str0m (required dependency for types and traits)
dimpl = { version = "0.2.0", default-features = false }

subtle = "2.0.0"

# For openssl errors
openssl = { version = "0.10.70", optional = true }
