[package]
name = "str0m-openssl"
version = "0.1.0"
edition = "2021"

[features]
vendored = ["openssl/vendored"]

[dependencies]
tracing = "0.1.37"
str0m-proto = { version = "0.1.0", path = "../../proto", features = ["openssl"] }
openssl = { version = "0.10.70" }
openssl-sys = { version = "0.9.80" }
libc = { version = "0.2" }
